### ISSUE TITLE
Problema a seguito rilevazione evento.

### ISSUE THREAD

**Issue by simmorga** [OpenQuake/D7S_Arduino_Library#2]
Ciao , 
Sto "giocherellando" con il sensore D7S, e in particolare con la tua libreria. 
Partendo dal tuo esempio che utilizza Arduino e due Interrupt trovo un problema . Ovvero, a seguito di rilevazione evento viene eseguita la funzione startEarthquakeHandler() e dopo circa due minuti Arduino esegue la funzione endEarthquakeHandler(). Per me, inspiegabilmente e senza apparente motivo, a distanza di qualche minuto o anche in maniera repentina Arduino ripropone nuovamente la funzione  endEarthquakeHandler() per due o tre volte quasi consecutive.
Il 328p che utilizzo è al 70% di memoria e 60% di Sram utilizzata. Pensavo potesse avere comportamenti inaspettati a seguito esaurimento risorse, ma non sembra. Cosa mi consigli di verificare ? Grazie.

Hello ,
I am "toying" with D7S sensor, and in particular with your library.
Starting from your example that uses Arduino and two Interrupt find it a problem. That is, as a result of event detection startEarthquakeHandler the function is executed () and after about two minutes Arduino executes the endEarthquakeHandler () function. For me, inexplicably and without apparent reason, at a distance of a few minutes or even in a sudden Arduino again repeats the endEarthquakeHandler () function to two or three times almost consecutive.
The 328P that utilization is at 70% and 60% of SRAM memory used. I thought it might have unexpected behavior due to depleting resources, but did not appear. What do you advise me to check? Thank you.

**Comment by simmorga** [comment]
Scusami. Ho notato che nel esempio con gli interrupt, a seguito di un evento sismico che attivi il PIN di evento, al termine restituisce sempre lo stesso valore SI e PGA, fatto salvo che l'evento successivo abbia un valore di PGA maggiore del precedente rilevamento. Ho notato che il valore non viene cancellato con un rese dell' Arduino ma solo  fino al riavvio a seguito di mancanza d'alimentazione.

I'm sorry. I noticed that in the example with interrupts, as a result of a seismic event that triggers the event PIN, at the end always returns the same value SI and PGA, except that the next event has a value of PGA greater than the previous detection. I noticed that the value is not erased with a yield of 'Arduino but only until restart after a power failure.

**Comment by alessandro1105** [comment]
Ciao,
sfortunatamente adesso non ho il tempo di verificare il problema.

Nel fine settimana cerco ti tirarmi fuori un'oretta per riprendere in mano il progetto e verificare il tuo problema.

Scusa per l'attesa,
Alessandro

**Comment by simmorga** [comment]
news ? confermo sia il primo che il secondo problema anche con un Maga2560... Grazie.

**Comment by alessandro1105** [comment]
Ciao simorga,
sono un annetto in riardo nel darti una risposta, è stato un periodaccio 😓 

Comunque per il secondo problema è il funzionamento stardard dell D7S, ovvero tiene in memoria gli ultimi eventi registrati (non ricordo esattamente quanti, ma mi sembra intorno a 5). Nella libraria c'è anche un metodo che permettere di leggere i dati degli eventi passati. 

Se avviene un'interruzione di alimentazione può essere che il D7S non abbia avuto il tempo di completare la sua procedura di "salvataggio", tieni presente che in media registra per circa 2 minuti.

Altra consiglio è questo: se per attivare il sensore dai un "pugno" sul tavolo no è detto che il sensore si comporti in modo corretto (l'ho provato di persona con valori "casuali"). Non ricordo esattamente ma per funzionare correttamente l'evento deve essere "prolungato nel tempo", ovvero esattamente come avviene in un evento sismico reale. Altro dettaglio che ricordo  è che se viene "triggerato" l'evento e successivamente il D7S decide che non era un evento sismico (ipotesi molto probabile con un "pugno sul tavolo") il metodo NON è in grado di determinare questa decisione del sensore e resituisce l'ultimo valore rilevato, ovvero quello dell'ultimo evento determinato dal sensore (e quindi salvato nella sua memoria).
