### ISSUE TITLE
Correction in selftest example

### ISSUE THREAD

**Issue by febalci** [OpenQuake/D7S_Arduino_Library#3]
https://github.com/alessandro1105/D7S_Arduino_Library/blob/e3b9dbd0b5bc88d6a496b32bd8b79997a65ac30e/examples/SelfDiagnostic/SelfDiagnostic.ino#L55

  if (D7S.getSelftestResult() == OK) {

Should be:

  if (D7S.getSelftestResult() == D7S_OK) {

**Comment by alessandro1105** [comment]
Hello febalci,
thanks to use my library and for your contribution. And I'm sorry to get back to you just now.

By the way you are totally right, that is a misspell and should be `D7S_OK`.

I'll fixit right now!
